version: 2
checks:
  argument-count:
    config:
      threshold: 3
  complex-logic:
    config:
      threshold: 4
  file-lines:
    config:
      threshold: 1000
  method-complexity:
    config:
      threshold: 5
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 150
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 4
exclude_patterns: 
  - ".vscode/"
  - "**/dist/"
  - "**/docs/"
  - "**/examples/"
  - "**/node_modules/"
  - "**/plugins/hammer/dist"
  - "**/scripts/"
  - "**/test/"
  - "**/tools/"
  - "**/aw.config.*.js"
