version: 2

jobs:
  build:
    working_directory: ~/picassojs
    # Available images https://hub.docker.com/r/circleci/node/tags/
    docker:
      - image: circleci/node:8.4.0-browsers
    steps:
      - checkout

      # Restore caches
      - restore_cache:
          key: v1-cache-{{ checksum "package-lock.json" }}
      - restore_cache:
          key: v1-cache-hammer-{{ checksum "plugins/hammer/package-lock.json" }}
      - restore_cache:
          key: v1-cache-q-{{ checksum "plugins/q/package-lock.json" }}
      - restore_cache:
          key: v1-cache-docs-{{ checksum "docs/package-lock.json" }}

      # Build all
      - run:
          name: Build all
          command: ./scripts/build-all.sh

      ## Save to cache
      - save_cache:
          key: v1-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - save_cache:
          key: v1-cache-hammer-{{ checksum "plugins/hammer/package-lock.json" }}
          paths:
            - ./plugins/hammer/node_modules
      - save_cache:
          key: v1-cache-q-{{ checksum "plugins/q/package-lock.json" }}
          paths:
            - ./plugins/q/node_modules
      - save_cache:
          key: v1-cache-docs-{{ checksum "docs/package-lock.json" }}
          paths:
            - ./docs/node_modules
      
      # Code validation
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Test
          command: npm run test:coverage
      - run:
          name: Integration test
          command: npm run test:integration:local
      - run:
          name: Publish coverage to code climate
          command: npm run test:unit:coverage:publish

      # Store artifacts
      - store_artifacts:
          path: package.json
      - store_artifacts:
          path: dist
      - store_artifacts:
          path: docs/dist
      - store_artifacts:
          path: test/unit/coverage
      - store_artifacts:
          path: test/component/coverage
      - store_artifacts:
          path: test/integration/coverage

